name: hypertext
description: Alternative HTTP protocol library for Dart.
version: 1.0.0-alpha
author: thosakwe <thosakwe@gmail.com>
homepage: https://github.com/thosakwe/hypertext

environment:
  sdk: '>=1.19.0'

dev_dependencies:
  angel_route: ^1.0.0
  http: ^0.11.0
  test: ^0.12.0
