name: hypertext
description: "Bare-metal, native-code, multi-threaded HTTP server for Dart. 🔥"
version: 0.0.1
author: thosakwe <thosakwe@gmail.com>
homepage: https://github.com/thosakwe/hypertext

environment:
  sdk: '>=2.0.0-dev.0 <3.0.0'

dev_dependencies:
  angel_route: ^1.0.0
  args: ^1.0.0
  http: ^0.11.0
  path: ^1.4.0
  test: ^0.12.0
